apply plugin: 'com.android.application'

android {
    namespace 'com.notification.timer'
    compileSdk 37

    signingConfigs {
        releaseConfig {
        }
    }
    defaultConfig {
        applicationId "com.notification.timer"
        minSdkVersion 23
        targetSdkVersion 37
        versionCode 10519
        versionName "1.5.19"
        multiDexEnabled true
    }
    flavorDimensions = ["versionCode"]
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }
    
    androidComponents {
        onVariants(selector().all(), { variant ->
            variant.outputs.forEach { output ->
                output.outputFileName.set("NotificationTimer.${android.defaultConfig.versionName}.apk")
            }
        })
    }

    sourceSets {
        main.res.srcDirs += 'src/main/res-betterpickers'
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.github.kizitonwose.colorpreference:core:1.0.5'
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
